### ISSUE TITLE
Will you release the dataset?

### ISSUE THREAD

**Issue by leonzfa** [intel-isl/MiDaS#1]
Great job! I wonder if the dataset will be released. It would help me a lot. Thanks very much.

**Comment by ranftlr** [comment]
Unfortunately, the circumstances surrounding copyright law prohibit direct distribution of the data. However, we plan to release the scripts that we used to produce the data set.

**Comment by mysunnyday** [comment]
@ranftlr  is there a time schedule ? current there is still only inference code :)
