### ISSUE TITLE
Torch hub not works for DPT

### ISSUE THREAD

**Issue by RuslanOm** [intel-isl/MiDaS#107]
Hi!

I'm trying to load dpt model from torch hub, but have this errors:

Downloading: "https://github.com/intel-isl/MiDaS/releases/download/v3/dpt_large-midas-2f21e586.pt" to /Users/ruslanom/.cache/torch/hub/checkpoints/dpt_large-midas-2f21e586.pt

and then 

    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by RuslanOm** [comment]
Oh, I see, last release in this repo is 2.1, but this model needs v3

**Comment by ranftlr** [comment]
You might need to update your cache ```torch.hub.list("intel-isl/MiDaS", force_reload=True)``` to refetch the hubconf definition.
