### ISSUE TITLE
Input size for training

### ISSUE THREAD

**Issue by mathmax12** [intel-isl/MiDaS#110]
@ranftlr Thanks for the great work.
I found the network's input doesn't have to be a fixed value and it seems the bigger size of the input the better estimation on the edge.
If I only want to do the inference on a 256x256x3 input size, during the training stage do I have to resize all the training samples to 256x256x3 and feed them to the network? Will train the model with a big input size (e.g. 512x512x3) and use the model for 256x256x3 case will give a better estimation?

Thanks.

**Comment by ranftlr** [comment]
Larger input size do look better as they lead to more accurate and fine edges, but have on average higher error. Humans are just not very good at judging the absolute quality of a depth map by just looking at it. You can find an evaluation of this effect in Figure 4 in our latest paper (https://arxiv.org/pdf/2103.13413.pdf).

We find that for best numerical accuracy you typically want to train at the resolution that you are testing at. So higher resolution training while evaluating at lower resolution likely will give you worse results.

**Comment by mathmax12** [comment]
Figure 4 is very helpful. That's a great contribution.  It also seems the lighter the network the higher that error. 
Thanks for the work.
