### ISSUE TITLE
What is the model_type for v2.1 large model in torch.hub?

### ISSUE THREAD

**Issue by Mofafa** [intel-isl/MiDaS#117]
Thanks for your great work!

**Comment by ranftlr** [comment]
It is simply ```model_type = MiDaS```

**Comment by Mofafa** [comment]
> It is simply `model_type = MiDaS`

Got it! 
Is v2.0 already removed in torch.hub?

**Comment by ranftlr** [comment]
v2.0 was removed from Hub. You can find it tagged as a release:

https://github.com/intel-isl/MiDaS/releases/tag/v2

**Comment by Mofafa** [comment]
> v2.0 was removed from Hub. You can find it tagged as a release:
> 
> https://github.com/intel-isl/MiDaS/releases/tag/v2

Thanks!
