### ISSUE TITLE
How to align the depth estimation of different MiDaS models?

### ISSUE THREAD

**Issue by 07hyx06** [intel-isl/MiDaS#120]
Hi! Thanks for your code!

My project uses the MiDaS v2 and I want to update it to the DPT-Large model, but their output range is quite different. It seems that the range of MiDaS v2 results lie in [0, 65536]. How can I align the results of MiDaS v2 and DPT-Large? What's the output range for the DPT-Large model? ( The project is related to some synthetic transformation so I just need the relative depth)

**Comment by ranftlr** [comment]
Both models output values between 0 and an arbitrarily large number. If it is just about aligning the ranges, you could simply normalize both predictions between 0 and some arbitrary maximum value like we do when displaying results: https://github.com/intel-isl/MiDaS/blob/bbe0b1004be9ebe199b86c9575214402c6177b1b/utils.py#L181

An alternative is to align one prediction to the other in a least-squares sense. See ```compute_scale_and_shift``` here:https://gist.github.com/ranftlr/45f4c7ddeb1bbb88d606bc600cab6c8d#file-validate_kitti-py-L67

**Comment by 07hyx06** [comment]
Thanks a lot!
