### ISSUE TITLE
What kind of activation function do you use during training?

### ISSUE THREAD

**Issue by zjjMaiMai** [intel-isl/MiDaS#15]
Hi, 
I see that relu is used during evaluation(this repo), What about training?
other question is that we do not include invalid pixels such as the sky when calculating the loss. 
How can we ensure that the network outputs the correct depth (zero or negative) for the background such as the sky?

**Comment by ranftlr** [comment]
We use the ReLU also during training to ensure positive disparity.

We set pixels that are part of the sky either to 0 disparity (infinite depth), or to the minimum disparity in the image in the case of the movies dataset.

**Comment by zjjMaiMai** [comment]
If the disparity of the sky is set to 0, are these disparity(ground truth) valid in mask?

**Comment by ranftlr** [comment]
Yes
