### ISSUE TITLE
How to covert RedWeb dataset label to disparity [0, 1]?

### ISSUE THREAD

**Issue by zjjMaiMai** [intel-isl/MiDaS#16]
Hi, 
In redweb dataset, the label is gived by a png file. nearest object depth is 0 and background depth is 255 (sky or something).
How to convert it to disparity [0, 1] as suggested in the paper? 
What about other dataset like MegaDepth?

Is my code correct?
```
eps = 0.1
label = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE).astype(np.float32)
sky_mask = (label == 255)
disparity = 1 / (label + eps)
disparity[sky_mask] = 0
disparity= (disparity - disparity.min()) / (disparity.max() - disparity.min())
```

**Comment by ranftlr** [comment]
ReDWeb is likely (negative) disparity. We are not 100% sure even after directly communicating with the authors of the original dataset. However, we use it as such in our code.  

For RedWeb, our code looks something like this:

```python
disp = np.array(imageio.imread(....))
mask = disp != 255

disp = disp / 255
disp *= -1.0
disp *= mask

min_val = np.min(disp)
max_val = np.max(disp)

disp = (disp - min_val) / (max_val - min_val)
```

For MegaDepth we first follow the filtering approach of the original authors
(https://github.com/zhengqili/MegaDepth/blob/master/data/image_folder.py) to get depth
and then compute:

```python
disp = np.zeros_like(depth)
disp[mask] = 1.0 / depth[mask]

min_val = np.min(disp)
max_val = np.max(disp)

disp = (disp- min_val) / (max_val - min_val)
```

**Comment by zjjMaiMai** [comment]
thx!
