### ISSUE TITLE
KITTI Numbers

### ISSUE THREAD

**Issue by anupamsobti** [intel-isl/MiDaS#18]
The KITTI set reported in the paper is said to have 161 images. 
(from Supplementary Material Section C,  

> "For KITTI we used the intersection of the official validation set for depth estimation (with improved ground-truth depth [69]) and the Eigen test split [60] (161 images)".)

I assume that is a mix of [Depth Benchmark Val](https://github.com/nianticlabs/monodepth2/blob/master/splits/benchmark/val_files.txt) and [Eigen Test](https://github.com/nianticlabs/monodepth2/blob/master/splits/eigen/test_files.txt). These seem to have only 145 common images. Could you please point me to the exact datasets that were used?

Here's the code I wrote to find the intersection
```python
#!/usr/bin/python
import re

benchmark_val_file = "splits/benchmark/val_files.txt"
eigen_test_file = "splits/eigen/test_files.txt"

zfill=True

with open(benchmark_val_file, 'r') as f:
    val_set= set()
    for line in f.readlines():
        dir_name, img_num = line.split()[:2]
        if zfill:
            val_set.add((dir_name, img_num.zfill(10)))
        else:
            val_set.add((dir_name, img_num))

with open(eigen_test_file, 'r') as f:
    eigen_set = set() 
    for line in f.readlines():
        dir_name, img_num = line.split()[:2]
        eigen_set.add((dir_name, img_num))

print(len(val_set.intersection(eigen_set)))

```

**Comment by lasinger** [comment]
It seems that there are some files missing in the list [Depth Benchmark Val](https://github.com/nianticlabs/monodepth2/blob/master/splits/benchmark/val_files.txt).
That list has only 6060 entries, but in the official test validation set from the [Kitti website](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction) ([Download annotated depth maps data set (14 GB)](http://www.cvlibs.net/download.php?file=data_depth_annotated.zip)) there are 6852 images.
Intersecting those 6852 images with the Eigen test split results in 161 images.

**Comment by anupamsobti** [comment]
Thank you for pointing that out.
