### ISSUE TITLE
Nice! Would you release your implementation of the loss function?

### ISSUE THREAD

**Issue by YotYot** [intel-isl/MiDaS#2]
I'm working on a relative article that use your great work, and would like to use your loss function.

Thanks in advance!

**Comment by dvdhfnr** [comment]
Hi! 
Please see: https://gist.github.com/dvdhfnr/732c26b61a0e63a0abc8a5d769dbebd0

**Comment by leonzfa** [comment]
@dvdhfnr I implemented the loss by myself. I found that the range of prediction is unstable. It can be -3~8, -10~30, -200~1000, in differernt training attempts. I wonder if your met the problem when you trained the network. Thank you very much.

**Comment by dvdhfnr** [comment]
No, I did not met this problem. Did you scale/shift the target depths to [0, 10], as described in the paper?

**Comment by leonzfa** [comment]
@dvdhfnr I train my model on NYUDepthV2, and scale/shift the depth value by
```
mask  = target > 0
target[mask] = (target[mask] - target[mask].min()) / (target[mask].max() - target[mask].min()) * 9 + 1
target[mask] = 10. / target[mask]
target[~mask] = 0.
```
How did you scale/shift the depth map?
----------
I have tried to use your loss code (image size = 224*288, and batch_size = 4), but got the following error:
```
*** RuntimeError: index 287 is out of bounds for dimension 0 with size 4
```
This error happens at the 22th line in midas_loss.py.
I use Python 3.7 and PyTorch 1.0.1.

**Comment by leonzfa** [comment]
@dvdhfnr I train my model on NYUDepthV2, and scale/shift the depth value by
```
mask  = target > 0
target[mask] = (target[mask] - target[mask].min()) / (target[mask].max() - target[mask].min()) * 9 + 1
target[mask] = 10. / target[mask]
target[~mask] = 0.
```
How did you scale/shift the depth map?
----------
I have tried to use your loss code (image size = 224*288, and batch_size = 4), but got the following error:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=59 : device-side assert triggered
*** RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317
```
This error happens at the 22th line in midas_loss.py.
I use Python 3.7.1 and PyTorch 1.0.1.

PS: If I use Python 3.6, I get "*** RuntimeError: index 287 is out of bounds for dimension 0 with size 4"
So is there any problem with the code?

**Comment by dvdhfnr** [comment]
To be more precise: 
"For all datasets, we shift and scale the ground-truth inverse depth to the range [0, 10]."

**Comment by leonzfa** [comment]
I test the provided midas_loss. It also leads to unstable output range. The output range is influenced by the initial weights.
I trained the network with different initial weights, and got the following results, in which the three numbers are the min, mean and max of prediction:
![Screenshot from 2019-07-17 16-15-54](https://user-images.githubusercontent.com/8134783/61395005-ff4a6e80-a8f6-11e9-99d5-3229e6d2f17a.png)
![Screenshot from 2019-07-18 00-53-04](https://user-images.githubusercontent.com/8134783/61395006-ffe30500-a8f6-11e9-8f66-067fed342d51.png)

**Comment by dvdhfnr** [comment]
The predictions resemble the target inverse depths up to a scale and shift.

**Comment by ranftlr** [comment]
As @dvdhfnr mentioned: This is by construction, as the value of the loss is independent of the output scale. Thus the ranges are dependent on the initialization. If you need a fixed scale range, you could try to add a (scaled) sigmoid to the output activations. However,  this might change training behavior and you likely need a sensible initialization.

**Comment by aiforworlds** [comment]
> Hi! Please see: https://gist.github.com/dvdhfnr/732c26b61a0e63a0abc8a5d769dbebd0

Hi this link is failed, could you share a new one 
Thanks.

**Comment by kebijuelun** [comment]
> To be more precise: "For all datasets, we shift and scale the ground-truth inverse depth to the range [0, 10]."

Hi, I found the  normalization range is [0, 1] in original paper, so which range is correct?

![image](https://user-images.githubusercontent.com/29164878/155270090-34f5a24c-946c-4c31-a544-6324c40c16d3.png)

thx

**Comment by dvdhfnr** [comment]
For the latest version of the paper we used the range [0, 1] (https://arxiv.org/pdf/1907.01341v3.pdf, Page 7). 

https://github.com/isl-org/MiDaS/issues/2#issuecomment-512181615 was referring to an earlier version.

**Comment by JohnG0024** [comment]
@dvdhfnr Hi, did you use [this loss function](https://gist.github.com/ranftlr/1d6194db2e1dffa0a50c9b0a9549cbd2) for MiDaS v3.0 as well?

**Comment by Twilight89** [comment]
@dvdhfnr @ranftlr Hi, 
I want to know how did you rescale the ground truths depth to range [0,1].
As my understanding, the following steps are done:
1. Get the ground truth inverse depth
2. Normalize like this **inverse_depth_normalization = (inverse_depth- inverse_depth.min()) / (inverse_depth.max() - inverse_depth.min())**

Does my understanding right? if not, could you please tell us how do you do "For all datasets, we shift and scale the ground-truth inverse depth to the range [0, 1]."?

Thx.

**Comment by CJCHEN1230** [comment]
@Twilight89 
Same problem
