### ISSUE TITLE
why use inverse depth ?

### ISSUE THREAD

**Issue by visonpon** [intel-isl/MiDaS#21]
Hi, @dvdhfnr I can't  understand why use inverse depth has difference with using original depth? or the inverse depth has some unique process? thanks~

**Comment by ranftlr** [comment]
Some datasets have been acquired with a stereo camera, but we don't have the calibration of the stereo rig. This means we can only get disparity, which is proportional to inverse depth. As it is straight-forward to go from depth to inverse depth, but not from disparity to depth, the inverse depth parametrization together with a loss that takes care of the scale and potentially shift follows as a natural middle-ground.

Inverse depth also has a couple of nice numerical properties. Points at infinity can be easily encoded and error distributions behave nicely and are approximately Gaussian, which makes learning easier. It has been used in the 3D reconstruction and SLAM communities for these reasons for many years.

**Comment by visonpon** [comment]
thanks for your explain in detail ,got it ~
