### ISSUE TITLE
How could I convert it to onnx model?

### ISSUE THREAD

**Issue by stereomatchingkiss** [intel-isl/MiDaS#22]
Trying to convert the model to onnx model, but got error 

  **File "to_onnx.py", line 72, in <module>
    export_model(model, img_input, export_model_name)
  File "to_onnx.py", line 30, in export_model
    torch.onnx.export(model, input, export_model_name, verbose=False, export_params=True, opset_version=11)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\jit\__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\jit\__init__.py", line 332, in forward
    in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type numpy.ndarray**

to_onnx.py

```
import os
import glob
import torch
import utils
import cv2

from torchvision.transforms import Compose
from models.midas_net import MidasNet
from models.transforms import Resize, NormalizeImage, PrepareForNet

import onnx
import onnxruntime

def test_model_accuracy(export_model_name, raw_output, input):    
    ort_session = onnxruntime.InferenceSession(export_model_name)

    def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    # compute ONNX Runtime output prediction
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input)}
    ort_outs = ort_session.run(None, ort_inputs)	

    # compare ONNX Runtime and PyTorch results
    np.testing.assert_allclose(to_numpy(raw_output), ort_outs[0], rtol=1e-03, atol=1e-05)

    print("Exported model has been tested with ONNXRuntime, and the result looks good!")		

def export_model(model, input, export_model_name):
    torch.onnx.export(model, input, export_model_name, verbose=False, export_params=True, opset_version=11)	
    onnx_model = onnx.load(export_model_name)    
    onnx.checker.check_model(onnx_model)
    graph_output = onnx.helper.printable_graph(onnx_model.graph)
    with open("graph_output.txt", mode="w") as fout:
        fout.write(graph_output)
		
device = torch.device("cpu")

 # load network
model_path = "model.pt"
model = MidasNet(model_path, non_negative=True)

transform = Compose(
        [
            Resize(
                384,
                384,
                resize_target=None,
                keep_aspect_ratio=True,
                ensure_multiple_of=32,
                resize_method="lower_bound",
                image_interpolation_method=cv2.INTER_CUBIC,
            ),
            NormalizeImage(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            PrepareForNet(),
        ]
)

model.to(device)
model.eval()

img = utils.read_image("input/line_up_00.jpg")
img_input = transform({"image": img})["image"]

# compute
#with torch.no_grad():
sample = torch.from_numpy(img_input).to(device).unsqueeze(0)
print("sample type = ", type(sample), ", shape of sample = ", sample.shape)
print(sample)	
prediction = model.forward(sample)
export_model_name = "midas.onnx"	
export_model(model, img_input, export_model_name)
```

Environment:

pytorch 1.4.0(installed by anaconda)
os is windows 10 64bits

**Comment by ranftlr** [comment]
Looking at the error message and you code, it seems that you are feeding a numpy array to ONNX converter.  My guess would be that the last line should be

```export_model(model, sample, export_model_name)```

If this doesn't solve your problem, I recommend asking in the PyTorch forums since this seems to be more related to ONNX/PyTorch than it is to our project.

**Comment by stereomatchingkiss** [comment]
> 
> 
> Looking at the error message and you code, it seems that you are feeding a numpy array to the ONNX converter. My guess would be that the last line should be
> 
> `export_model(model, sample, export_model_name)`
> 
> If this doesn't solve your problem, I recommend asking in the PyTorch forums since this seems to be more related to ONNX/PyTorch than it is to our project.

Type of the sample is tensor

`sample = torch.from_numpy(img_input).to(device).unsqueeze(0)`

It is weird to have a error message like that

**Comment by stereomatchingkiss** [comment]
My bad, export_model function do input numpy but not tensor, thanks for the tips.

After I change it to sample but not img_input, the error message change to

```
 %1162 : Float(1, 128, 384, 576) = onnx::Upsample[mode="linear"](%1135, %1161) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\functional.py:2530:0
  %1163 : Float(1, 32, 384, 576) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%1162, %scratch.output_conv.2.weight, %scratch.output_conv.2.bias) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\modules\conv.py:342:0
  %1164 : Float(1, 32, 384, 576) = onnx::Relu(%1163) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\functional.py:912:0
  %1165 : Float(1, 1, 384, 576) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%1164, %scratch.output_conv.4.weight, %scratch.output_conv.4.bias) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\modules\conv.py:342:0
  %1166 : Float(1, 1, 384, 576) = onnx::Relu(%1165) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\functional.py:912:0
  %1167 : Float(1, 384, 576) = onnx::Squeeze[axes=[1]](%1166) # C:\Users\yyyy\programs\Qt\app_to_simplify_ml\cv_projects\clients\mobile_depth_estimation\MiDaS\models\midas_net.py:76:0
  return (%1167)

```

I post the bug at [pytorch forum](https://github.com/pytorch/pytorch/issues/36069) too

**Comment by stereomatchingkiss** [comment]
I can convert the model after I change opset to 11.

`torch.onnx.export(model, input, export_model_name, verbose=False, export_params=True, opset_version=11)	`

But the precision test fail

```
export_model(model, sample, export_model_name)
test_model_accuracy(export_model_name, prediction, sample)

```
**Traceback (most recent call last):
  File "to_onnx.py", line 78, in <module>
    test_model_accuracy(export_model_name, prediction, sample)
  File "to_onnx.py", line 26, in test_model_accuracy
    np.testing.assert_allclose(to_numpy(raw_output), ort_outs[0], rtol=1e-03, atol=1e-05)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\numpy\testing\_private\utils.py", line 1548, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\numpy\testing\_private\utils.py", line 861, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 168755 / 221184 (76.3%)
Max absolute difference: 0.28403193
Max relative difference: 810.0278
 x: array([[[0.098411, 0.08588 , 0.086399, ..., 0.02793 , 0.      ,
         0.      ],
        [0.039169, 0.049598, 0.057025, ..., 0.      , 0.      ,...
 y: array([[[0.      , 0.      , 0.      , ..., 0.      , 0.      ,
         0.      ],
        [0.      , 0.      , 0.      , ..., 0.      , 0.      ,...**

**Comment by stereomatchingkiss** [comment]
Not sure why, but export again fix the bug

**Comment by l0stpenguin** [comment]
@stereomatchingkiss can you share the working script or the converted onnx file? 
Thanks

**Comment by stereomatchingkiss** [comment]
> 
> 
> @stereomatchingkiss can you share the working script or the converted onnx file?
> Thanks

Sure, you can get it from [this post](https://github.com/opencv/opencv/pull/17030)

**Comment by l0stpenguin** [comment]
@stereomatchingkiss I tried to convert to onnx model to coreml since i wanted to try it on ios but it onnx-coreml failed:
```
TypeError: Error while converting op of type: Slice. Error message: Input shape not available 
```
So i thought maybe your generated model has some issues. So I tried your script _to_onnx.py_ to generate the onnx model again. The conversation is successful but _onnxruntime_ fails to evaluate it:
```
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Resize node. Name:'' Status Message: /Users/runner/runners/2.165.1/work/1/s/onnxruntime/core/providers/cpu/tensor/upsample.h:281 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float> &, const onnxruntime::UpsampleMode) const scales.size() == 2 || (scales.size() == 4 && scales[0] == 1 && scales[1] == 1) was false. 'Linear' mode and 'Cubic' mode only support 2-D inputs ('Bilinear', 'Bicubic') or 4-D inputs with the corresponding outermost 2 scale values being 1 in the Resize operator
```
Did you run into this issue when validating it via _onnxruntime_?

**Comment by stereomatchingkiss** [comment]
> Did you run into this issue when validating it via _onnxruntime_?

No, you could check the codes of test_accuracy, everything is fine. Maybe it is a bug of onnx-coreml, please check the link I send you and open a similar issue on the issue list of onnx-coreml.

**Comment by l0stpenguin** [comment]
> > Did you run into this issue when validating it via _onnxruntime_?
> 
> No, you could check the codes of test_accuracy, everything is fine. Maybe it is a bug of onnx-coreml, please check the link I send you and open a similar issue on the issue list of onnx-coreml if needed, thanks

Thanks for the advice. I opened an issue on onnx-coreml github:
https://github.com/onnx/onnx-coreml/issues/563
