### ISSUE TITLE
Testing code

### ISSUE THREAD

**Issue by FilippoAleotti** [intel-isl/MiDaS#29]
Hi,
I'm having some problems in obtaining your same results at testing time. Could you share also an example of a script (e.g, NYU or TUM would be great) to test your network, please?

**Comment by ranftlr** [comment]
Do you mean a scripts to produce the quantitative results (i.e. the numbers) on NYU or TUM?

**Comment by FilippoAleotti** [comment]
Yes, if possible

**Comment by ranftlr** [comment]
Please see here for an example: 

https://gist.github.com/ranftlr/a1c7a24ebb24ce0e2f2ace5bce917022

It reproduces the results for NYU (Table 7 - first row in the paper).

**Comment by FilippoAleotti** [comment]
Thank you!
