### ISSUE TITLE
About getting results in meters unit

### ISSUE THREAD

**Issue by nightheronry** [intel-isl/MiDaS#37]
@ranftlr Thank you for the work. I'm trying to apply it with Myriad X VPU.
So I would like to ask whether the unknown scale and shift mentioned in #36 are linear parameters?
For example, in each frame, I can find a linear equation like "P = D * scale + shift" to project the values of depth maps "D" to the physical absolute measurements "P" according to putting a known scale ruler in the view, right ?

**Comment by ranftlr** [comment]
Yes, they are linear parameters. When doing alignment, consider that P and D are _inverse_ depth so you need to convert your absolute measurements to inverse depth first.

**Comment by nightheronry** [comment]
@ranftlr Thank you for your kind reply !! :)

**Comment by rodrigoGA** [comment]
If I understand correctly ...
P = is in  inverse depth = 1/ physical distance in meters
D= inverse depth = result of the inference. It does not need inverse, the model already predicts the inverse
scale and shift = are estimated with least squares from known points in the image

Can I calibrate "scale and" shift "and use the model in an environment with the same lighting? Or is it necessary to calibrate in each frame?

**Comment by mahavir-GPI** [comment]
@rodrigoGA Did you get the correct scale and shift values based on the approach you mentioned?

**Comment by rodrigoGA** [comment]
according to my tests the model is very inaccurate to measure distance (uncalibrated  in each frame ).
It's a shame, because it has very good runtimes and is compatible with tensorflow lite.
According to the internet there are approaches that take into account the previous frame that achieve better results

**Comment by mahavir-GPI** [comment]
Oh, To confirm, by uncalibrated do you mean you didn't calculate the scale and shift value? Did you directly use the model predicted values?

**Comment by puyiwen** [comment]
> Yes, they are linear parameters. When doing alignment, consider that P and D are _inverse_ depth so you need to convert your absolute measurements to inverse depth first.

Hi, sorry to  bother you. I use depth camera D435i , but the depth map is bad. So I want to use MiDaS to improve the quality of the depth map. I write the scrips to align the MiDaS and absolute depth map. 
I need to confirm something. The alignment formula is **y = kx + b**, **y** means invert absolute depth with meters, **x** means the prediction of MiDaS, **k** means scale and **b** means shift. Am I right?
The align code is:
`realsense_depth_array_invert = 1 / realsense_depth_array # invert absolute depth with meters`
`x = midas_depth_array.copy().flatten() #Midas Depth`
`y = realsense_depth_array_invert.copy().flatten()  # Realsense invert Depth`
`A = np.vstack([x, np.ones(len(x))]).T`
`s, t = np.linalg.lstsq(A, y, rcond=None)[0]`
`midas_depth_aligned_invert = midas_depth_array * s + t`
`midas_depth_aligned = 1 / midas_depth_aligned_invert`
The `midas_depth_aligned` is finally absolute depth with meters. Am I right?
If I am right, I find aligned depth have large error. I dont know why, can you help me? Thank you very much!

**Comment by putrasto** [comment]
@rodrigoGA  i think you need to calculate "scale" and "shift" for each image we can not use them for other image because "D" is normalized.

**Comment by Shubhamkumarroy** [comment]
> @ranftlr Thank you for the work. I'm trying to apply it with Myriad X VPU. So I would like to ask whether the unknown scale and shift mentioned in #36 are linear parameters? For example, in each frame, I can find a linear equation like "P = D * scale + shift" to project the values of depth maps "D" to the physical absolute measurements "P" according to putting a known scale ruler in the view, right ?

and can we use scale and shift ,same for all image if i have calculated using it two image if not then so for every image i have to calculate the scale and shift so how can it be don?
