### ISSUE TITLE
Wrong predictions?

### ISSUE THREAD

**Issue by aizuon** [intel-isl/MiDaS#38]
I did a test run with a book on a flat surface. On the output the background depth isn't uniform. Is there something I'm missing?
[
![image](https://user-images.githubusercontent.com/44760523/89661028-d8345580-d8da-11ea-9933-4a0dbff3b035.png)
](url)

**Comment by ranftlr** [comment]
While the model is robust, it doesn't provide correct predictions in all conceivable circumstances - this is an open research problem.  

The sample that you provided here is very challenging. There are few depth cues and no context in the image. The scene is uncommon or even non-existent in the datasets that the model was trained on. I wouldn't expect MiDaS (or any existing monocular depth estimation model) to work well for this image. A typical image where MiDaS works well in most cases is your average vacation photo, a photo of a room or street scene, a photo showing people or animals, etc. We also discuss some common failure cases in the supplementary material of our paper.
