### ISSUE TITLE
Camera Intrinsics

### ISSUE THREAD

**Issue by barnjamin** [intel-isl/MiDaS#4]
Here is a visualization of the combined rgb image taken with my phone and depth inferred by MiDaS.
![image](https://user-images.githubusercontent.com/520236/61453308-c7a9e980-a92b-11e9-9e7b-e1241d5d42d8.png)

I used the intrinsic values from the phone camera but I'm not sure that makes sense to do since the depth projects out to much greater than the ground truth. 

Is the depth just relative within the image or should I expect to be able to achieve a realistic rough depth value?

**Comment by barnjamin** [comment]
For reference, here is what I used to generate the above
```
import open3d as o3d
import glob

intrinsic = o3d.io.read_pinhole_camera_intrinsic("intrinsic.json")

c_imgs = glob.glob("./input/*.png")
c_imgs.sort()

d_imgs = glob.glob("./output/*.png")
d_imgs.sort()


for idx in range(10):
    color = o3d.io.read_image(c_imgs[idx])
    depth = o3d.io.read_image(d_imgs[idx])
    
    rgbdi = o3d.geometry.create_rgbd_image_from_color_and_depth(color, depth, depth_trunc=50)
    pcd = o3d.geometry.create_point_cloud_from_rgbd_image(rgbdi, intrinsic)
    o3d.visualization.draw_geometries([color, pcd])
```

**Comment by ranftlr** [comment]
The output is relative inverse depth up to scale, so you'll have to guess the intrinsics.

Additionally, it seems that Open3D requires depth as input, but our output is inverse depth. The following code gives decent results on COCO with a principal point in the center of the image and a focal length of anywhere between 500 and 1000 (depending on the image):

```
import open3d as o3d
import numpy as np
import glob

from utils import read_pfm

intrinsic = o3d.read_pinhole_camera_intrinsic("intrinsics.json")

c_imgs = glob.glob("./input/*.jpg")
c_imgs.sort()

d_imgs = glob.glob("./output/*.pfm")
d_imgs.sort()

for idx in range(len(c_imgs)):
    color = o3d.read_image(c_imgs[idx])
    idepth = read_pfm(d_imgs[idx])[0]

    idepth = idepth - np.amin(idepth)
    idepth /= np.amax(idepth)

    focal = intrinsic.intrinsic_matrix[0, 0]
    depth = focal / (idepth)
    depth[depth >= 5 * focal] = np.inf

    depth = o3d.Image(depth)

    rgbdi = o3d.create_rgbd_image_from_color_and_depth(color, depth)
    pcd = o3d.create_point_cloud_from_rgbd_image(rgbdi, intrinsic)
    o3d.draw_geometries([pcd])
```

**Comment by barnjamin** [comment]
Great, thank you! Any tips for guessing the intrinsics? Is that an active area of research that you know of?
