### ISSUE TITLE
No such file or directory: 'model-f46da743.pt'

### ISSUE THREAD

**Issue by GregoryBetsey** [intel-isl/MiDaS#41]
Hello

I got this error. Did I put the .pt file in wrong location? (see attachment)

initialize
device: cuda
Loading weights:  model-f46da743.pt
Using cache found in C:\Users\gregb/.cache\torch\hub\facebookresearch_WSL-Images_master
Traceback (most recent call last):
  File "run.py", line 105, in <module>
    run(INPUT_PATH, OUTPUT_PATH, MODEL_PATH)
  File "run.py", line 29, in run
    model = MidasNet(model_path, non_negative=True)
  File "C:\Users\gregb\Documents\Python\MiDaS\midas\midas_net.py", line 47, in __init__
    self.load(path)
  File "C:\Users\gregb\Documents\Python\MiDaS\midas\base_model.py", line 11, in load
    parameters = torch.load(path)
  File "C:\Users\gregb\anaconda3\envs\3DP\lib\site-packages\torch\serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\gregb\anaconda3\envs\3DP\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\gregb\anaconda3\envs\3DP\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model-f46da743.pt'

![Untitled](https://user-images.githubusercontent.com/40677608/90942645-daff7200-e3d3-11ea-82ac-5271705988b6.png)

**Comment by kjyothiswaroop** [comment]
Hey Gregory, I am getting a similar error, though i am running the code on  Ubuntu. what is the fix for the issue?

**Comment by 3dsf** [comment]
@kjyothiswaroop 

You either have to call the `run.py` file from the same folder or you have the wrong model present.  In the example above, the script was calling a different model than was present.

**Comment by Davidesteve1850** [comment]
Hi gregory, I'm trying to "play" with a repository that uses the same weights but the link they provided has been broken and the creator doesn't seem to have updated it. Could you please send me a copy of the pesos? 
Thank you

**Comment by GregoryBetsey** [comment]
> Hi gregory, I'm trying to "play" with a repository that uses the same weights but the link they provided has been broken and the creator doesn't seem to have updated it. Could you please send me a copy of the pesos? Thank you

Hello. Are you asking for model-f46da743.pt?
