### ISSUE TITLE
How can I visualize the point cloud?

### ISSUE THREAD

**Issue by dldl3D** [intel-isl/MiDaS#5]
Hi,

Thanks for your great work. I want to know how I can visualize the point cloud from the depth image by Open3D. According the [Camera Intrinsics](https://github.com/intel-isl/MiDaS/issues/4), I don't know the content of the intrinsics.json file. Could you give me an example of this file?
Another question, when do you plan to release the scripts that used to produce the data set?

Thank you very much!

**Comment by barnjamin** [comment]
it follows the format for open3d intrinsic file 
something like this:
```
{
	"height" : 480,
	"intrinsic_matrix" : 
	[
		610.0023193359375,
		0.0,
		0.0,
		0.0,
		609.85760498046875,
		0.0,
		425.36004638671875,
		237.9273681640625,
		1.0
	],
	"width" : 848
}
```

**Comment by dldl3D** [comment]
Thanks for your reply. The height of image is 1440, and the width is 1080. How can I get the intrinsic matrix?

**Comment by paruliansaragi** [comment]
How did you get it to output a point cloud?

**Comment by barnjamin** [comment]
@dldl3D please refer to this section describing intrinsic parameters.  You'll have to find out what they are from the make/model of the camera you're using or do camera calibration to figure them out. 

That said, the output is inferred depth that does not correspond exactly with the intrinsic parameters of the camera.  

https://en.wikipedia.org/wiki/Camera_resectioning#Intrinsic_parameters

@paruliansaragi the output is an inferred depth image that can be projected into 3D space forming a point cloud.  I used Open3D but the output does not correspond exactly with the intrinsic parameters.

see here: https://github.com/intel-isl/MiDaS/issues/4
