### ISSUE TITLE
Depth map estimated distance

### ISSUE THREAD

**Issue by liweilup** [intel-isl/MiDaS#52]
Hello, the project I am working on requires a monocular camera to estimate the distance of the object. The general method is to obtain the depth value from the depth camera and then calculate the distance according to the camera_factor. But I did not see this related variable in the paper. I know if I can use the depth generated by this network to estimate the distance. I am a student who has just learned knowledge in this field. Hope to get help. Thank you

**Comment by ranftlr** [comment]
MiDaS provides ***relative*** (inverse) depth. See #37 and #42 for similar discussions and relation to absolute distances.

**Comment by liweilup** [comment]
@ranftlr 
Thank you very much for your answer, it helped me a lot
