### ISSUE TITLE
Pre-trained model on Pytorch hub not updated

### ISSUE THREAD

**Issue by saturn660** [intel-isl/MiDaS#55]
Loading the pre-trained model from Pytorch hub tries to use this link [github.com/intel-isl/MiDaS/releases/download/v2_1/model-f6b98070.pt](https://github.com/intel-isl/MiDaS/releases/download/v2_1/model-f6b98070.pt) and fails. This file does not exist as the model file seems to have been updated. Please make relevant changes so that the model can be loaded from Pytorch hub.

**Comment by ranftlr** [comment]
You were faster than my internet connection could upload. The link works now.
