### ISSUE TITLE
warning: Could not initialize NNPACK!

### ISSUE THREAD

**Issue by 3dsf** [intel-isl/MiDaS#57]
`python run.py --model_weights model-small-70d6b9c8.pt --model_type small`

> initialize
> device: cuda
> Loading weights:  model-small-70d6b9c8.pt
> Downloading: "https://github.com/rwightman/gen-efficientnet-pytorch/archive/master.zip" to ~/.cache/torch/hub/master.zip
> **[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.**
> start processing
>   processing input/rifb7z5sepy51.jpg (1/1)
> finished
 
--- 

The requirements for NNPACK are
- L3 cache
- AVX2 

which this cpu does not meet.  

**Besides a loss of some speed, should I expect other performance variances?**

I still get results in the output folder that are consistent with what I'd expect in comparison to the larger model.

**Comment by ranftlr** [comment]
No, I don't expect a difference. NNPACK is just  another back end. The back ends are unit tested in PyTorch and should be equivalent in functionality up to small stochastic differences. When NNPACK is not available, PyTorch will fall back to THNN. This might be slower as you mentioned, but will implement the same operation. If you don't want to trust the PyTorch devs on this, you can read and run the unit tests yourself to check.

Looking at the PyTorch code, depending on your platform and compile flags, it might be disabled anyway, even if it were available. See the check for a batch size >= 16, which comes after ```_nnpack_available``` (which is generating the warning):

https://github.com/pytorch/pytorch/blob/2397c8d1f78cb5b48bcec9c180c1eef81c13b887/aten/src/ATen/native/Convolution.cpp#L250-L264

```c
auto ConvParams::use_nnpack(const at::Tensor& input) const -> bool {
#if AT_NNPACK_ENABLED()
  return at::_nnpack_available() &&
         input.options().backend() == at::Backend::CPU &&
         input.scalar_type() == kFloat && // only on CPU Float Tensors
         !is_dilated() && // or dilation
         !transposed &&   // or transposed tensors
         input.ndimension() == 4 // must be in NCHW format
#if !defined(C10_MOBILE) && !defined(CAFFE2_FB_LIMITED_MOBILE_CAPABILITY)
         && input.size(0) >= 16 // ensure large enough batch size to ensure perf, tuneable
#endif
     ;
#endif
  return false;
}
```

**Comment by 3dsf** [comment]
Great, 
thanks for the thorough explanation.
