### ISSUE TITLE
Anything new with v2.1 except training on 10 datasets?

### ISSUE THREAD

**Issue by mangdian** [intel-isl/MiDaS#59]
Thanks for your wonderful work!

I tested v2.1 on my own data and it is much better! Is there anything different with v2.1 ? Except training on more datasets.

**Comment by ranftlr** [comment]
For the large "default" model: no, everything stayed the same, except for the additional datasets.

Other than that: we now provide a light-weight, real-time model and support additional platforms. Have a look at the Changelog for an overview.
