### ISSUE TITLE
What does run.py script return?

### ISSUE THREAD

**Issue by RomanovMikeV** [intel-isl/MiDaS#6]
Hi! I am trying to get your repository working in a simple inference mode to be able to estimate the quality on NYUv2 dataset. As far as I understand, your run.py script returns inverse logarithm of depth scaled by some coefficient. Am I right? (At least that gives the best metrics, though I saw that you said that you predict the inverse depth)

Also, I have yet another question: you take as a backbone ResNet network. But, as far as I understand, you use it for the unnormalized images (i.e, images that do not have 0 mean intensities and unit stds), while the ResNet was trained on normalized images. Is this right and why do you do that?

**Comment by ranftlr** [comment]
The network was trained to predict inverse depth up to unknown scale and shift (no logarithm), so measuring errors requires to align to the ground truth both in scale and shift. We did this in inverse depth space for all datasets for the sake of simplicity. You might get lower numbers on NYU if you directly align in depth space.  

Regarding normalization: Correct, we use unnormalized images. There is no specific reason for that. It seems that the network trains equally well without the normalization. Note that the backbone is adapted during training.
