### ISSUE TITLE
nan value in the output of model

### ISSUE THREAD

**Issue by mathmax12** [intel-isl/MiDaS#60]
Thanks very much for the work.
It's much accurate than before.

But in some cases, there are "nan" values in the output of the model.
![image](https://user-images.githubusercontent.com/32367611/99465353-0e786c80-28ef-11eb-9206-8c9160b0cecb.png)
This is the test image I used.
![input_video_screenshot](https://user-images.githubusercontent.com/32367611/99465435-48497300-28ef-11eb-9c76-44cce34e511a.png)
Seems the old version doesn't have this issue.

**Comment by ranftlr** [comment]
I can't reproduce your issue with the image you posted. Can you provide some additional information?

Specifically:

- What model are you using (standard or small)?
- What platform (PyTorch, Tensforflow, one of the others)? What is the version of the platform?
- Is the image you posted exactly the one where you observed the issues? 
- Do you do any additional pre- or post-processing?
- Are you running on CPU or GPU?

**Comment by mathmax12** [comment]
Thanks for reply.
Please view the answer as below.

> I can't reproduce your issue with the image you posted. Can you provide some additional information?
> 
> Specifically:
> 
> * What model are you using (standard or small)?
- I am using the model-f6b98070.pt standard one.
> * What platform (PyTorch, Tensforflow, one of the others)? What is the version of the platform?
-I am using Pytorch
     >>> import torch
     >>> print(torch.__version__)
     1.7.0a0+19fb0b8
> * Is the image you posted exactly the one where you observed the issues?
-Yes
> * Do you do any additional pre- or post-processing?
-No. I used the code without any change
 python run.py --model_weights ../models/model-f6b98070.pt 
> * Are you running on CPU or GPU?
-On GPU

**Comment by mathmax12** [comment]
I just tried to swtich the device to "CPU" and there is no such issue
#device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    device = torch.device("cpu")

The python and opencv versions:
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
>>> import cv2
>>> cv2.__version__
'3.4.11'
>>>

**Comment by ranftlr** [comment]
Thanks. Unfortunately, I still can't reproduce it.

I notice the ```a0+19fb0b8``` suffix in your PyTorch version string. The current PyTorch 1.7.0 stable release doesn't have this suffix (it only prints ```1.7.0```). You might be running an older unstable pre-release. Could you try to upgrade to the latest stable release and retry?

**Comment by mathmax12** [comment]
Thanks. I will have a try.
