### ISSUE TITLE
Midas v2.1 tensorflow model

### ISSUE THREAD

**Issue by tholmb** [intel-isl/MiDaS#61]
First of all, thanks for the great project!

It looks like f46da743.pb is the newest tf model [1) Download the model weights [model-f45da743.pb] (https://github.com/intel-isl/MiDaS/releases/download/v2/**model-f46da743.pb**)]. I assume that this model is MiDaS v2.0 since I downloaded this same model one month ago. Do you have any plans to train MiDaS v2.1 also with tensorflow?

**Comment by ranftlr** [comment]
Thanks for pointing this out. The README still linked to the old model. I've updated the links to the new models.

**Comment by tholmb** [comment]
Thanks for the fast reply!
