### ISSUE TITLE
404 error when trying to download tflite model

### ISSUE THREAD

**Issue by wpmed92** [intel-isl/MiDaS#64]
I tried to run the android sample but https://github.com/intel-isl/MiDaS/releases/download/v2/model_opt.tflite throws 404 error.

**Comment by ranftlr** [comment]
I've fixed the link, please try again

**Comment by wpmed92** [comment]
Meanwhile I managed to download the test apk, decompile it, and get the model from it, but thank you for updating the url, it's working now!

Any suggestion on how I could further decrease the model size?

**Comment by coralexbadeaYonder** [comment]
Hello can you provide the model again, it does not work. Thanks for your work.

**Comment by wpmed92** [comment]
The link is: https://github.com/isl-org/MiDaS/releases/download/v2_1/model_opt.tflite
