### ISSUE TITLE
how to train the groudtrue disparity from PWC

### ISSUE THREAD

**Issue by perrywu1989** [intel-isl/MiDaS#7]
Hello, 

Thanks for releasing the code.What an amazing project you did!
There I have some questions. I can not get perfect groundtrue disparity maps as you did. I hope to have your help.
1. how to modify the pwc-net code. replace the 2dcorrealtion with 1dcorrlation or not?
2. train the pwc-net code in supervised mode or unsupervised mode?
3. if train pwc-net code in unsupervised mode, what is the unsupervised loss you used?
4. can you release the trained model of your pwc-net?
Thanks very much.

Perry

**Comment by ranftlr** [comment]
We do not retrain PWC-Net. We use an off-the-shelf model (https://github.com/NVlabs/PWC-Net/tree/master/PyTorch) and use the horizontal component as disparity.

**Comment by perrywu1989** [comment]
Thanks for your reply.
