### ISSUE TITLE
How to extract the .egg file in DIML dataset?

### ISSUE THREAD

**Issue by lvzhengyi0204** [intel-isl/MiDaS#78]
Hi:
    It took a long time to download the DIML dataset. But I can’t open the .egg format file. How did you decompress this format file?
    I tried the unzip command, but it didn't work

**Comment by panji530** [comment]
hi, have you figured out how to extract the .gg file in DIML?

**Comment by marcelsan** [comment]
Do you guys have any update on this?

**Comment by manuelknott** [comment]
Same issue here. Does anyone know a solution?
