### ISSUE TITLE
input tensor name ?

### ISSUE THREAD

**Issue by Titibo26** [intel-isl/MiDaS#80]
Hi, 
I'm trying to test midas model with tensorflowsharp in .net c#.

I'm facing an exception  `TensorFlow.TFGraph.this[string].get returned null.` when i add a tensor image as input :
`runner.AddInput(graph["image"][0], MyInputTensorImage);`
Apparently this means that the tensor input name is wrong.
As the documentation says here : [https://docs.openvinotoolkit.org/latest/omz_models_public_midasnet_midasnet.html](url) it should be "image" right ?

Thank you

**Comment by jankais3r** [comment]
Try `input_image`

**Comment by Titibo26** [comment]
Well, when reading .ONNX graphs with netron, input is "0" and output is "1080" for the big model or "797" for the small model.
Thank you,
